name: CI/CD Pipeline


  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout Code
      uses: actions/checkout@v3

   
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

  
    - name: Build Docker Image
      run: |
        docker build -t reddit-app .
    
    
    - name: Test Container Startup
      run: |
        docker run -d --name test-container -p 8000:8000 reddit-app
        sleep 5
        docker ps | grep test-container
        docker stop test-container

    
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_HOST }}      # Your EC2 IP Address
        username: ${{ secrets.AWS_USER }}  # usually 'ubuntu'
        key: ${{ secrets.AWS_PRIVATE_KEY }} # Your .pem key
        script: |
          # Stop the old container
          docker stop reddit-app || true
          docker rm reddit-app || true
          # Start the new one
          docker run -d --name reddit-app -p 8000:8000 my-docker-hub-user/reddit-app:latest